#!/bin python3

from mathics_scanner.characters import replace_wl_with_plain_text as r
from mathics_scanner.characters import aliased_characters

def escape(s: str) -> str:
    """Escaped special chracters in inputrc strings"""
    return s.replace("\\", "\\\\").replace("\"", "\\\"")

def format(c: str, use_unicode: bool) -> str:
    """Formats a single key-value pair"""
    key = escape(c)
    val = escape(r(aliased_characters[c], use_unicode=use_unicode))

    return f'"\\e{key}\\e": "{val}"\n'

# Generate inputrc-unicode
with open("mathicsscript/inputrc-unicode", "w") as f:
    f.write("# GNU Readline input translations\n\n")
    f.write("# Lowercase TeX Greek characters\n")
    f.write("$include inputrc-greek-letters\n\n")
    f.write("# Autogenerated with mathics-scanner\n")

    for alias in aliased_characters:
        f.write(format(alias, use_unicode=True))

# Generate inputrc-no-unicode
with open("mathicsscript/inputrc-no-unicode", "w") as f:
    f.write("# GNU Readline input translations\n\n")
    f.write("# Autogenerated with mathics-scanner\n")

    for alias in aliased_characters:
        f.write(format(alias, use_unicode=False))

