#!/bin python3

from mathics_scanner.characters import replace_wl_with_plain_text as r
from mathics_scanner.characters import aliased_characters as a

def escape(s: str) -> str:
    """Escaped special chracters in inputrc strings"""
    return s.replace("\\", "\\\\").replace("\"", "\\\"")

# Generate inputrc-unicode
with open("mathicsscript/inputrc-unicode", "w") as f:
    f.write("# GNU Readline input translations\n\n")
    f.write("# Lowercase TeX Greek characters\n")
    f.write("$include inputrc-greek-letters\n\n")
    f.write("# Autogenerated with mathics-scanner\n")

    for alias in a:
        f.write(
            f'"\\e{escape(alias)}\\e": "{escape(r(a[alias], use_unicode=True))}"\n'
        )

# Generate inputrc-no-unicode
with open("mathicsscript/inputrc-no-unicode", "w") as f:
    f.write("# GNU Readline input translations\n\n")
    f.write("# Autogenerated with mathics-scanner\n")

    for alias in a:
        f.write(
            f'"\\e{escape(alias)}\\e": "{escape(r(a[alias], use_unicode=False))}"\n'
        )

