name: mathicsscript (OSX)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        brew install asymptote
        python3 -m pip install --upgrade pip
        # Can comment out when next Mathics core and Mathics-scanner are released
        # python3 -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner[full]
        # python -m pip install -e git+https://github.com/Mathics3/mathics-core#egg=Mathics3[full]
        git clone https://github.com/Mathics3/mathics-core
        (cd mathics-core && pip3 install -e .[full])
        (cd mathics-core && bash ./admin-tools/make-op-tables.sh)
        # python -m pip install Mathics3[full]
    - name: Install mathicsscript
      run: |
        make
    - name: Test mathicsscript
      run: |
        pip3 install -r requirements-dev.txt
        make check
